### PR TITLE
ci: add release workflows

### PR DESCRIPTION
**Pull request by voneiden**

### CODE REVIEW

**Comment by voneiden** [comment]
requested access to https://test.pypi.org/project/gdpr-api-tester/

**Comment by akikoskinen** [comment]
Can the workflow be run - perhaps just to test PyPI - before merging?

**Comment by voneiden** [comment]
https://github.com/City-of-Helsinki/profile-gdpr-api-tester/actions/runs/7346394576/job/20001076560?pr=11 looks OK to me. Currently do not have permissions to upload to the test PyPi as devhel but that's a known issue and in progress.

**Comment by akikoskinen** [comment]
> https://github.com/City-of-Helsinki/profile-gdpr-api-tester/actions/runs/7346394576/job/20001076560?pr=11 looks OK to me. Currently do not have permissions to upload to the test PyPi as devhel but that's a known issue and in progress.

OK. I guess it's good then. Do remove the last commit and this can be merged.

**Review by nicobav — APPROVED** [review]
LOKTM! 👍

**Pull request merged**
